// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcS7YOHLoyO5R79xMuvsY7oU0ExJtdnMI',
    appId: '1:854360588026:web:3ae28d181add5ae6845343',
    messagingSenderId: '854360588026',
    projectId: 'rsii-dc04a',
    authDomain: 'rsii-dc04a.firebaseapp.com',
    storageBucket: 'rsii-dc04a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-doLx8aPXo2Y-f-9U1U27iJSVOhrJTrU',
    appId: '1:854360588026:android:e1ca45cd0712dde0845343',
    messagingSenderId: '854360588026',
    projectId: 'rsii-dc04a',
    storageBucket: 'rsii-dc04a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbXO_ChmKb_eyx-zwkSzgyVC4dnyXsdYM',
    appId: '1:854360588026:ios:1e22e52b433b9e5a845343',
    messagingSenderId: '854360588026',
    projectId: 'rsii-dc04a',
    storageBucket: 'rsii-dc04a.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbXO_ChmKb_eyx-zwkSzgyVC4dnyXsdYM',
    appId: '1:854360588026:ios:1e22e52b433b9e5a845343',
    messagingSenderId: '854360588026',
    projectId: 'rsii-dc04a',
    storageBucket: 'rsii-dc04a.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcS7YOHLoyO5R79xMuvsY7oU0ExJtdnMI',
    appId: '1:854360588026:web:4fa281234570d9e2845343',
    messagingSenderId: '854360588026',
    projectId: 'rsii-dc04a',
    authDomain: 'rsii-dc04a.firebaseapp.com',
    storageBucket: 'rsii-dc04a.firebasestorage.app',
  );
}
