services:

  zenyoga-database:
    image: mcr.microsoft.com/mssql/server:2022-CU23-ubuntu-22.04
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - 14533:1433
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S zenyoga-database -U sa -P ${MSSQL_SA_PASSWORD} -Q "SELECT 1" -C
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - zenyoga-network

  zenyoga-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - AzureBlobStorage__ConnectionString=${AZURE_BLOB_CONNECTION_STRING}
      - AzureBlobStorage__UserPhotosContainer=${AZURE_BLOB_USER_PHOTOS_CONTAINER}
      - AzureBlobStorage__StudioPhotosContainer=${AZURE_BLOB_STUDIO_PHOTOS_CONTAINER}
      - RabbitMQ__Host=${RABBITMQ_HOST}
      - RabbitMQ__Port=${RABBITMQ_PORT}
      - RabbitMQ__User=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
      - RabbitMQ__QueueName=${RABBITMQ_QUEUE}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - HashingSettings__Salt=${HASHING_SALT}
      - StripeSettings__SecretKey=${STRIPE_SECRET_KEY}
      - StripeSettings__StripeVersion=${STRIPE_VERSION}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - 8080:8080
    networks:
      - zenyoga-network
    depends_on:
      zenyoga-database:
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      zenyoga-network:
        aliases:
          - rabbitmq

  zenyoga-worker:
    build:
      context: .
      dockerfile: Worker-Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - RabbitMQ__Host=${RABBITMQ_HOST}
      - RabbitMQ__Queue=${RABBITMQ_QUEUE}
      - StripeSettings__SecretKey=${STRIPE_SECRET_KEY}
      - StripeSettings__StripeVersion=${STRIPE_VERSION}
    networks:
      - zenyoga-network
    depends_on:
      zenyoga-database:
        condition: service_healthy
      rabbitmq:
        condition: service_started

networks:
  zenyoga-network:
    driver: bridge